### PR TITLE
Fresh Paint

### PR DESCRIPTION
**Pull request by jenius**
A little update to some styles and colors and a few bugfixes. Looks a lot smoother now :grinning: 

Voice any concerns within 24h or this ish is getting merged!

### CODE REVIEW

**Comment by dbox** [comment]
Sorry thought this was axi

**Comment by dbox** [comment]
Hahah. Phone fail

**Comment by dbox** [comment]
Hey- Looks good. I should have more time to dive in further later today.

One quick thing: I would make `nav ul li` be `font-size: .9375rem` (rem15px) or `font-size: 1rem` at most.

**Comment by dbox** [comment]
What about a subtle gradient vs going with 100% the same color as that other library? 
image

Having monospaced fonts for these headers seems out of place:
image

I'm not sure about the "yelling" buttons. All caps can definitely work but not at those sizes.
image

Small todo: need to match favicon to new scheme. I can do.

**Comment by dbox** [comment]
I'd also lighten nav bg slightly. The end.

**Comment by jenius** [comment]
Yes. Great suggestions, will implement these today. This is why axis needs you :grin:

**Comment by jenius** [comment]
Ah and for the buttons, I'm planning on increasing the padding a bit within axis itself to make this look more natural

**Comment by dbox** [comment]
👍 I did it in code, so I can pr tonight.

**Comment by jenius** [comment]
Got a chunk of it ready, will push in a moment!

**Comment by jenius** [comment]
Ah we also need to update the favicon color

**Comment by dbox** [comment]
Yeah, I said that! :)

**Comment by jenius** [comment]
Can't get anything by you these days haha

**Comment by dbox** [comment]
19 years in the business ;)

**Comment by jenius** [comment]
Ok, looking pretty good to me at this point. Add anything else you'd like!

**Comment by jenius** [comment]
This will also be good prep for the big port to postcss and release thing, which honestly I feel like will be happening fairly soon :grinning:

**Comment by jenius** [comment]
I'm going to take a pass on axis itself modernizing some of the older ui and type pieces as well, I'll ping you there when it's ready. Probably we should push a 1.0 release too, since this has been stable and in use in the wild for quite a while. Postcss could be the `2.0`. Thoughts?

**Comment by dbox** [comment]
Sounds great.

**Comment by dbox** [comment]
1.0 was a long time coming.

**Comment by dbox** [comment]
adding a commit standby

**Pull request merged**
