### PR TITLE
Rem-calculator, Quantity queries, and dependency bumps

### PR DESCRIPTION
**Pull request by dbox**

### CODE REVIEW

**Comment by dbox** [comment]
haha. misspelled calculator on the commit. it's fine in the code. i am NOT going to rebase this :dash:

**Comment by dbox** [comment]
Should it auto-fire a netlify build @jenius? Doesn't seem to have updated.

**Comment by jenius** [comment]
Yeah it looks like it failed due to a jade marked filter issue. Trying a re-trigger now.

**Comment by jenius** [comment]
Yup rebuild failed, "unknown filter marked". Any ideas?

**Comment by declandewet** [comment]
the jade `:markdown` filter was deprecated, now you gotta use `:marked` - perhaps, Netlify has an old version of Roots and thus Accord that does not support the new `:marked` filter

**Comment by dbox** [comment]
I updated the dependencies so it wouldn't throw the error on the local
build any more... Not sure what needs to be done on netlify side.

**Comment by dbox** [comment]
But happy to look into it if you want me to. My netlify info is daniel@kurtnoble.com / dbox

**Comment by jenius** [comment]
Sent you an invite for the netlify site. Thanks for checking this out, really appreciate it. Sorry I haven't been as responsive, sadly I just don't have that much time this year

**Comment by dbox** [comment]
Netlify's version of roots for the axis site definitely seems older:

Axis logs:
`5:43:03 PM > roots@3.0.2 postinstall /opt/build/repo/node_modules/roots > node ./post_install.js`

Another roots project I have:
`9:22:37 AM > roots@3.1.0 postinstall /opt/build/repo/node_modules/roots > node ./post_install.js`

I do have roots as a dependency on that project and roots is in the package.json file. 
Is it possible for me to force an update of roots on Netlify's side or do I need to contact them to do that?

**Comment by jenius** [comment]
I'd contact them about it, they resolve stuff like this super quick

**Comment by dbox** [comment]
yeah i'm emailing with him now. Is there a reason you do NOT want to have roots as a dependency in package.json?

**Comment by dbox** [comment]
Basically it sounds like if we add roots to package.json as 3.1.0 it will fix it. Otherwise he has to manually change some stuff...

**Comment by dbox** [comment]
From Mathias:

"No, I would recommend adding that line.

In fact I suspect that the current build kinda works by accident. My guess would be that one of the dependencies in the package requires roots. We add node_modules/.bin to the PATH before the build, so that's where the roots command gets picked up from (we don't have a global version of roots installed).

Explicitly requiring roots in the package.json makes sure you're in control of exactly what version of roots actually ends up as the one being used during the build and is definitively the right way to go.

Cheers,
Mathias"

Gunna try this..

**Comment by jenius** [comment]
Yeah it was an oversight not adding roots to package.json. Adding it should
do the trick!

**Comment by dbox** [comment]
That got us up to roots 3.1 but still throwing an error. Still looking into it..

---
Daniel Box

615.414.9651 <tel:615.414.9651>
danielbox@gmail.com <http://danielbox@gmail.com/>
@dbox <http://twitter.com/dbox>

**Comment by dbox** [comment]
The weird thing is its flawless locally...

**Comment by dbox** [comment]
http://axis.netlify.com/

Fixed. new goods are up. :100:

**Comment by jenius** [comment]
Whoo! Thanks for taking care of that. :hand:

**Pull request merged**
