### PR TITLE
Fresh paint tweaks

### PR DESCRIPTION
**Pull request by dbox**
some nitpicky creative director tweaks..

Thought it might be good to do a dark theme for code blocks but I'll save that for another day :)

### CODE REVIEW

**Comment by jenius** [comment]
Ok so I'm down for all of this, only thing I'm slightly not sold on is how small the nav is on the left. Also while we're here might as well do the dark code blocks. That was a good suggestion, I feel like it will look nice. Whoever gets to it first we can take it from there :grin:

**Comment by dbox** [comment]
Oh, hello. 1:37am. Elliott "Axis" Box decided to wake up. Nav just seemed
like it was scaled up and out of proportion imho. Meet in the middle?

Jk, this is your thing. W/e you like is fine.

For code blocks I was going to do something similar to Atom's default dark
theme.

**Comment by dbox** [comment]
Oh, also: creenshot me what you're seeing just in case.

**Comment by dbox** [comment]
http://atom.github.io/highlights/examples/

monokai :100:

**Comment by dbox** [comment]
Check that out and see what you think. There are a few other little touches I think we could do, but I can do it next time I update docs.

**Comment by jenius** [comment]
This looks good. Let's get it shipped! :shipit:

**Comment by dbox** [comment]
🐣

**Comment by declandewet** [comment]
Nice work! :clap:  Big fan of the new colors :+1:

**Pull request merged**
