### PR TITLE
0.5.0

### PR DESCRIPTION
**Pull request by dbox**
Still working on this. Don't merge yet. But feel free to pull it down and add/ edit anything that you want.

Cleaned this up so it works with 0.5.0 and updated all the docs to have proper variable names. 

I still need to add documentation for:
- rule
- hover-glow, hover-float
- click-down(),click-inset(), click-shadow(), & click-shrink()
-table layout

### CODE REVIEW

**Comment by dbox** [comment]
This is probably good to go. Feel free to pull it down and take a look, or I'll push it live later tonight or tomorrow. 
I temporarily got rid of npm shrinkwrap, but I can put it back if it starts being weird on netlify.

**Comment by dbox** [comment]
Having weird netlify issues again. yay!

**Comment by dbox** [comment]
docs for 0.5.0 are published. :tada: 

Will start work on 0.5.1 additions now :)

**Comment by jenius** [comment]
Sweet! Browsed through quickly and didn't see `global-reset` or any of the `position` utilities, or any of the other stuff we ported from nib. Just a note that we should add these at some point!

**Comment by dbox** [comment]
ohhhhh yeahhhh.Will add.

**Comment by dbox** [comment]
Might be nice to have a little writeup about the settings too

**Pull request merged**
